const HeaderActionTypes = {
  TOGGLE_MENU_HIDDEN: 'TOGGLE_MENU_HIDDEN',
  SET_MENU_HIDDEN: 'SET_MENU_HIDDEN',
  TOGGLE_LOGIN_HIDDEN: 'TOGGLE_LOGIN_HIDDEN',
  SET_LOGIN_HIDDEN: 'SET_LOGIN_HIDDEN',
  TOGGLE_USER_HIDDEN: 'TOGGLE_USER_HIDDEN',
  SET_USER_HIDDEN: 'SET_USER_HIDDEN',
};

export default HeaderActionTypes;
