const UserActionTypes = {
  LOG_IN_START: 'SIGN_IN_START',
  LOG_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOG_OUT_START: 'LOG_OUT_START',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
};

export default UserActionTypes;
